title: Zhixing Sun 孙知行
position: Master's Student
affiliation: Brandeis University
email: sun3@brandeis.edu
keywords: Zhixing Sun academic
google_scholar: https://scholar.google.com/citations?user=9xV-rmoAAAAJ&hl=zh-CN&oi=ao
github_link: https://github.com/oscarsun19
linkedin: https://www.linkedin.com/in/ziao-yang-a1a13a223/
avatar: ./assets/img/Photo_own.png
google_analytics: UA-111540567-
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The oscarsun19  is a simple and elegant jekyll theme for academic personal homepage.

